<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-41VTHPF" failures="1" tests="1" name="Test" time="3.438" errors="0" timestamp="2022-08-26T09:12:01 AST">
  <testcase classname="testcases.VerifyDBData" name="verifyDbData" time="0.383">
    <failure type="java.sql.SQLException" message="Operation not allowed after ResultSet closed">
      <![CDATA[java.sql.SQLException: Operation not allowed after ResultSet closed
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:485)
at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:580)
at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851)
at dbConnection.DBConnection.GetDBData(DBConnection.java:40)
at testcases.VerifyDBData.verifyDbData(VerifyDBData.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyDbData -->
</testsuite> <!-- Test -->
